/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Clear: typeof import('./src/components/Icons/Clear.vue')['default']
    Doc: typeof import('./src/components/Icons/Doc.vue')['default']
    Github: typeof import('./src/components/Icons/Github.vue')['default']
    IFluentPrint28Regular: typeof import('~icons/fluent/print28-regular')['default']
    IGgHello: typeof import('~icons/gg/hello')['default']
    Paint: typeof import('./src/components/Paint.vue')['default']
    Save: typeof import('./src/components/Icons/Save.vue')['default']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCard: typeof import('@varlet/ui')['_CardComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarOption: typeof import('@varlet/ui')['_OptionComponent']
    VarSelect: typeof import('@varlet/ui')['_SelectComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
  }
}
